import type { Metadata } from "next"
import { Comic_Neue } from "next/font/google"
import "./globals.css"

const comicNeue = Comic_Neue({ subsets: ["latin"], weight: ["400", "700"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={comicNeue.className}>{children}</body>
    </html>
  )
}
